image: gitpod/workspace-full

tasks:
  - init: npm install --legacy-peer-deps
    command: npm run develop

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
