# .gitpod.yml (프로젝트 루트에 덮어쓰기)
image: mcr.microsoft.com/vscode/devcontainers/javascript-node:18

tasks:
  - init: |
      # 1) 빌드 필수툴 + Python2.7 설치
      sudo apt-get update
      sudo apt-get install -y build-essential python2.7-minimal python2-minimal
      # node-gyp이 'python' 커맨드를 Python2로 쓰도록 링크
      sudo ln -sf /usr/bin/python2.7 /usr/bin/python

      # 2) 의존성 설치 (legacy-peer-deps)
      npm install --legacy-peer-deps

    # 3) 개발 서버 자동 실행
    command: npm run develop -- --host 0.0.0.0

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
